Risk dashboard overview page
mars-protocol/mars-rd-fe pull request #1
Opened 2024-07-22 11:52 UTC by Patricie29

This PR deploys the initial setup of the Risk Dashboard overview page, focusing on visual analytics and token metrics.

- `MetricsCard` -  reusable component to display key statistics, currently with placeholder data.
- `TokenMetrics` - floating `Card` displaying up to date token information 
- Charts with Tabbed Navigation: Includes demo charts within a tab interface for future data representation (Line Chart, Bar Chart)
- Dropdown Time Filter Chart: A chart with time interval selections (1H, 1D, 1W, 1Y), pre-loaded with dummy data.

2024-07-24 19:05 UTC, linkielink requested changes
Great work!
All I found were some improvements of the codequality, but mostly only based on personal preference (or the "rules", we agreed on internally).

2024-07-24 19:05 UTC, linkielink commented on src/hooks/tokenomics/useTotalSupply.ts
> +}
By using `useSWRImmutable` this hook will never update during the users session. It is unlikely, that the total supply ever updates, after it was fetched once.

```suggestion
import getTotalSupply from 'api/tokenomics/getTotalSupply'
import useSWRImmutable from 'swr/immutable'

export default function useTotalSupply() {
  return useSWRImmutable('tokenomics/totalSupply', async () => getTotalSupply())
}
```

2024-07-24 19:05 UTC, linkielink commented on src/types/app.d.ts
> +}
This change was introduced by me and can be undone
```suggestion
interface Store extends CommonSlice, ModalSlice {}
```

2024-07-25 18:35 UTC, Patricie29 commented on src/api/tokenomics/getMarsTokenPrice.ts
> +    const marsToken = data.find((token: Token) => token.symbol === 'MARS')
Got it, will change it.

2024-07-25 18:41 UTC, Patricie29 commented on src/components/common/Card/MetricsCard.tsx
> +      className={`flex flex-col justify-between mx-auto my-5 p-5 ${className}`}
right, yes I remember you saying this as well.

2024-07-25 19:06 UTC, Patricie29 commented on src/api/tokenomics/getMarsTokenPrice.ts
> +}
yess

2024-07-26 07:42 UTC, Patricie29 commented on src/components/main/StatsMetrics.tsx
> +      ]}
yess, I'll keep it as it is now and once I have the data, will update it

2024-07-30 11:55 UTC, linkielink requested changes

2024-07-30 11:55 UTC, linkielink commented on src/components/common/Chart/BarChart/BarChartBody.tsx
> +  }
This will rerender on every update.

Move the function out of the `BarChartBody` function and create a component function for it.
E.g.: create the `function TollTipContent` on line 13 having the same content as it has now. You also don't need to wrap it in a fragment, as a `map` function can stand alone without a wrapper.

2024-07-30 11:55 UTC, linkielink commented on src/components/common/Chart/ChartBody.tsx
> +
```suggestion
  function TooltipContent(props: {payload: ChartDataPayloadProps[]}) {
    const { payload } = props
    const value = Number(payload[0].value) ?? 0
    return (
      <Text size='sm'>{formatValue(value, { minDecimals: 0, maxDecimals: 0, prefix: '$' })}</Text>
    ) 
```

Convert this function into a component function.

2024-07-30 11:55 UTC, linkielink commented on src/components/common/Chart/DuoLineChart/index.tsx
> +  }
Convert into a component function outside of the `DuoLineChart`

2024-07-30 11:55 UTC, linkielink commented on src/components/common/Chart/DuoLineChart/index.tsx
> +function RenderLegend(props: RenderLegendProps) {
```suggestion
function DouLineChartLegend(props: DouLineChartLegendProps) {
```

2024-08-01 09:08 UTC, linkielink approved these changes

2024-08-01 09:09 UTC, merged